### ISSUE TITLE
setSmallIcon()没有生效

### ISSUE THREAD

**Issue by notxx** [oasisfeng/nevolution#21]
试图做个Decorator来搞定MIUI中难看的彩色小图标，不过setSmallIcon()似乎不生效（改color、title和largeIcon都生效了……）。
```java
    @Override
    protected void apply(MutableStatusBarNotification evolving) {
        final MutableNotification n = evolving.getNotification();
        Log.d(TAG, "begin modifying");
        Icon icon = Icon.createWithResource(this, R.drawable.ic_stat_name);
        n.extras.putParcelable("nevo.icon", icon);
        n.extras.putParcelable("android.icon", icon);
        n.setSmallIcon(icon);
        n.setLargeIcon(icon);
        n.color = Color.RED;
        n.extras.putCharSequence(Notification.EXTRA_TITLE, "title replaced");
        Log.d(TAG, "end modifying");
    }
```
这是为啥呢

**Comment by oasisfeng** [comment]
是仅在 MIUI 上不生效，还是在其它设备（比如官方模拟器）上亦不生效？

**Comment by notxx** [comment]
找了个类原生（ZUK Z2 Pro，AEX）测试了一下（替换pushbullet的通知），也不生效，内源和外源都不行。截图如下，第二个通知是为了确认配套资源文件正确用普通方式发的。
![Screenshot_20190522-224620_Pixel_Launcher](https://user-images.githubusercontent.com/785476/58184454-b35abf00-7ce3-11e9-8691-7b791df50d9e.png)

**Comment by oasisfeng** [comment]
谢谢反馈！问题已确认，将在下个版本中修复。

**Comment by oasisfeng** [comment]
验证修复并继续插件开发，可使用以下测试版本：
[Nevolution.fix.for.setSmallIcon.zip](https://github.com/Nevolution/sdk/files/3220946/Nevolution.fix.for.setSmallIcon.zip)

**Comment by notxx** [comment]
测试了一下MIUI下内源模式OK
