### ISSUE TITLE
AndroidManifest.xml中的service::meta-data[name=package]应该怎么用

### ISSUE THREAD

**Issue by notxx** [oasisfeng/nevolution#22]
我试着抄了一下decorator-wechat的
`<meta-data android:name="packages" android:value="com.xiaomi.xmsf" />`
这样在女娲石新增配方的时候很方便，直接可以给小米服务框架加修饰器。
但是这样的效果是只有小米服务框架可以用这个修饰器，其他包用不了了。
有没有办法可以既方便新增，又可以让别的包用这个修饰器呢

**Comment by oasisfeng** [comment]
这个 meta-data 只适用于定向插件，无法兼顾通用插件和定向插件的需求。

目前 Nevolution 已经支持插件主动请求将自身加入指定应用的配方，具体的 API 已更新到 [Wiki](https://github.com/Nevolution/sdk/wiki/Decorator-Plugin-Development)。

另外，建议加入 README 中提到的 Telegram 上的开发者讨论群以进行更为实时的沟通。
