### ISSUE TITLE
What is this permission request?

### ISSUE THREAD

**Issue by techmagus** [oasisfeng/nevolution#24]
Hi,

With the latest Nevolution release in the Beta channel, there is this new permission request that does not make sense.

"Permission required to read notification channels (Click to pick any device to grant permission)"

However, once the said notification was tapped, what it displays are WiFi hotspots the phone can detect, not devices.

Secondly, the WiFi setting is off so I don't understand how the new Nevolution can detect the WiFi around me.

Third, if the app is opening the WiFi setting, it is not getting reflected anywhere nor were there permission requests to turn-on the WiFi.

Lastly, what "devices" was it supposed to display? Was it supposed to detect bluetooth devices?

Thank you for the clarifications.

Great update.

**Comment by techmagus** [comment]
![Screenshot_20190910-201010](https://user-images.githubusercontent.com/1079205/64612902-6864d480-d3c4-11e9-9676-54829f4d22b1.png)

WiFi is off but Nevo is using WiFi to detect hotspots.

**Comment by oasisfeng** [comment]
It's a workaround to correctly query notification channels of other apps on Android 9+.

This Android mechanism itself is designed for device companion app (like app for smart watch). Nevolution just uses its API for querying notification channels.
