### ISSUE TITLE
打开兼容模式后按home键会自动打开Android Auto的驾驶模式

### ISSUE THREAD

**Issue by qsdaqsdafqr** [oasisfeng/nevolution#29]
打开兼容模式后按home键会自动打开Android Auto的驾驶模式，退出驾驶模式又会自动关闭兼容模式，原生安卓11和EMUI11都出现了这个问题

**Comment by oasisfeng** [comment]
插件相关的问题，请反馈至对应插件的 issue tracker。

比如 微信插件：https://github.com/Nevolution/decorator-wechat/issues
