### ISSUE TITLE
onNotificationRemoved() not fired when bubble visible

### ISSUE THREAD

**Issue by MolotovCherry** [oasisfeng/nevolution#31]
On the latest dev version, when a bubble is showing, `onNotificationRemoved()` will not fire until the bubble is removed. Not sure whether this is a bug or not. I tested this with the wechat decorator specifically.

**Comment by oasisfeng** [comment]
I think that's the intented behavior in AOSP.

Nevolution just forwards the `onNotificationRemoved()` call.

**Comment by MolotovCherry** [comment]
I thought that might be the case!
