### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by Agoines** [oasisfeng/nevolution#32]
我有个问题想请教下oasisfeng大大，女娲石和绿色守护还会短期内是否还会进行更新？
如果不进行更新了，是否考虑过开源让其他人继续进行维护？

**Comment by oasisfeng** [comment]
会更新，但不会频繁。

女娲石采用插件机制，具体功能层面主要靠插件，第三方开发者可以使用 SDK 进行插件开发。
