### ISSUE TITLE
Android 13 beta 无法通过通知回复

### ISSUE THREAD

**Issue by steve1145114** [oasisfeng/nevolution#33]
![Screenshot_20220703-183326](https://user-images.githubusercontent.com/89009827/177035745-dba13882-a5ea-4982-a871-cd4bce0b9665.png)
![Screenshot_20220703-183323~2](https://user-images.githubusercontent.com/89009827/177035749-e5520923-0c36-4daf-b111-d860b9018f26.png)

**Comment by steve1145114** [comment]
Android 13 (TPB3.220617.002)

**Comment by oasisfeng** [comment]
插件问题请反馈到对应插件的 repo。

BTW，这是微信较新版本的限制，与 Android 13 无关。

**Comment by Ben-md5** [comment]
打开兼容模式就好了

**Comment by oasisfeng** [comment]
目前官方没有提供 QQ 的通知插件，如果是第三方插件，请反馈给插件开发者。
