### ISSUE TITLE
Make multiple plug-ins visible

### ISSUE THREAD

**Issue by licaon-kter** [oasisfeng/nevolution#8]
By adding some sort of info or arrows that encourages the user to scroll left/right on the card to switch between them.

I, for one, thought there was only 1 plug-in (whatever random one I got when opening the app).

**Comment by skiman6010** [comment]
I would say it would be better to have the plugins on both sides almost "peek in". Meaning just show a little sliver on each side of the one that is being shown up front.

**Comment by oasisfeng** [comment]
It's implemented in the newest preview version. Thanks for your suggestion.
